{% set name = "pept" %}
{% set version = "0.2.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 03efcab9245f1917e49db45d5d87e172e8dc219df0b02b4da0fb23f10cdf0cf9

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython >=0.29.13
    - numpy
    - pip
    - python
  run:
    - cython >=0.29.13
    - hdbscan >=0.8.26
    - joblib >=0.13.2
    - matplotlib-base >=3.1.1
    - {{ pin_compatible('numpy') }}
    - plotly >=4.4.1
    - python
    - scipy >=1.3.1
    - six >=1.12.0
    - tqdm >=4.41.1
    - pandas >=1.0.5

test:
  imports:
    - pept
    - pept.base
    - pept.cookbook
    - pept.diagnostics
    - pept.scanners
    - pept.scanners.modular_camera
    - pept.scanners.parallel_screens
    - pept.simulation
    - pept.tracking
    - pept.tracking.birmingham_method
    - pept.tracking.peptml
    - pept.tracking.trajectory_separation
    - pept.utilities
    - pept.utilities.cutpoints
    - pept.utilities.misc
    - pept.utilities.parallel
    - pept.utilities.traverse
    - pept.visualisation

about:
  home: https://github.com/uob-positron-imaging-centre/pept
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: >
    A Python library that unifies Positron Emission Particle Tracking (PEPT)
    research, including tracking, simulation, data analysis and visualisation
    tools.
  doc_url: https://pept.readthedocs.io/en/latest/
  dev_url: https://github.com/uob-positron-imaging-centre/pept

extra:
  recipe-maintainers:
    - anicusan
    - smngr
