{% set name = "pept" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c955d2a271e503c7d94d2fad121024952aafd78f4d36344ccbcf5c122d098ee5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython >=0.29.14
    - numpy
    - pip
    - python
  run:
    - cython >=0.29.14
    - hdbscan >=0.8.26
    - joblib >=0.15.1
    - matplotlib-base >=3.2.2
    - {{ pin_compatible('numpy') }}
    - plotly >=4.4.1
    - python
    - scipy >=1.4.1
    - six >=1.12.0
    - tqdm >=4.41.1
    - pandas >=1.0.5
    - cma >=3.0.3

test:
  imports:
    - pept
    - pept.base
    - pept.cookbook
    - pept.diagnostics
    - pept.scanners
    - pept.scanners.modular_camera
    - pept.scanners.parallel_screens
    - pept.simulation
    - pept.tracking
    - pept.tracking.birmingham_method
    - pept.tracking.peptml
    - pept.tracking.fpi
    - pept.tracking.trajectory_separation
    - pept.processing
    - pept.utilities
    - pept.utilities.cutpoints
    - pept.utilities.misc
    - pept.utilities.parallel
    - pept.utilities.traverse
    - pept.visualisation

about:
  home: https://github.com/uob-positron-imaging-centre/pept
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: >
    A Python library that unifies Positron Emission Particle Tracking (PEPT) research, including tracking, simulation, data analysis and visualisation tools.
  doc_url: https://pept.readthedocs.io/en/latest/
  dev_url: https://github.com/uob-positron-imaging-centre/pept

extra:
  recipe-maintainers:
    - anicusan
    - smngr
